---
kind: pipeline
type: kubernetes
name: default

trigger:
  branch: [main]

workspace:
  path: /go/src/github.com/${DRONE_REPO}

volumes:
  - name: cache
    temp: {}

steps:
  - name: test
    image: golangci/golangci-lint:v1.45.2
    volumes:
      - name: cache
        path: /go
    commands:
      - make test
