package cli

import (
	"github.com/spf13/pflag"
)

// Args holds the generator configuration. It replaces k8s.io/gengo/args,
// which was removed in gengo/v2 in favor of passing options directly to
// gengo.Execute.
type Args struct {
	InputDirs          []string
	OutputFileBaseName string
	GeneratedBuildTag  string
}

func flagLogLevel(flags *pflag.FlagSet) {
	flags.StringP("log-level", "v", "info", "Configure log level")
}

func flagGeneratorArgs(fs *pflag.FlagSet, g *Args) {
	fs.StringSliceVarP(&g.InputDirs, "input-dirs", "i", g.InputDirs, "Comma-separated list of import paths to get input types from.")
	fs.StringVarP(&g.OutputFileBaseName, "output-file-base", "O", g.OutputFileBaseName, "Base name (without .go suffix) for output files.")
	fs.StringVar(&g.GeneratedBuildTag, "build-tag", g.GeneratedBuildTag, "A Go build tag to use to identify files generated by this command. Should be unique.")
}
