package cli

import (
	"fmt"
	"strings"

	"github.com/kanopy-platform/code-generator/pkg/generators"
	"github.com/kanopy-platform/code-generator/pkg/generators/builder"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	gengo "k8s.io/gengo/v2"
)

type rootCommand struct {
	GeneratorArgs *Args
}

func WithGeneratorArgs(g *Args) func(*rootCommand) {
	return func(r *rootCommand) {
		r.GeneratorArgs = g
	}
}

func NewRootCommand(opts ...func(*rootCommand)) *cobra.Command {
	rootCommand := &rootCommand{
		GeneratorArgs: &Args{},
	}

	for _, opt := range opts {
		opt(rootCommand)
	}

	rootCommand.GeneratorArgs.OutputFileBaseName = "zz_generated_builders"
	// Add a header to generated files so gengo will ignore them to reduce
	// parse time. gengo/v2 never parses _test.go files.
	rootCommand.GeneratorArgs.GeneratedBuildTag = "ignore_autogenerated"

	cmd := &cobra.Command{
		Use:               "kanopy-codegen",
		Short:             "Kanopy Builder code generator",
		PersistentPreRunE: rootCommand.prerun,
		RunE:              rootCommand.runE,
	}

	rootCommand.setupFlags(cmd)

	return cmd
}

func (r *rootCommand) setupFlags(cmd *cobra.Command) {
	flags := cmd.PersistentFlags()
	flagLogLevel(flags)
	flagGeneratorArgs(flags, r.GeneratorArgs)
}

func (r *rootCommand) prerun(cmd *cobra.Command, args []string) error {

	if err := viper.BindPFlags(cmd.PersistentFlags()); err != nil {
		return err
	}

	return setupGlobalLogLevel()
}

func (r *rootCommand) runE(cmd *cobra.Command, args []string) error {
	headerLines := []string{
		fmt.Sprintf("//go:build !%s\n", r.GeneratorArgs.GeneratedBuildTag),
		"/* DO NOT EDIT */",
		"/* autogenerated by kanopy-platform/code-generator */",
		"\n",
	}

	g := generators.New(&builder.BuilderPatternGeneratorFactory{OutputFileBaseName: r.GeneratorArgs.OutputFileBaseName},
		generators.WithBoilerplate(strings.Join(headerLines, "\n")))
	return gengo.Execute(
		generators.NameSystems(),
		generators.DefaultNameSystem,
		g.Targets,
		r.GeneratorArgs.GeneratedBuildTag,
		r.GeneratorArgs.InputDirs,
	)
}

func setupGlobalLogLevel() error {
	// set log level
	logLevel, err := log.ParseLevel(viper.GetString("log-level"))
	if err != nil {
		return err
	}

	log.SetLevel(logLevel)
	return nil
}
