package cli

import (
	"fmt"
	"strings"

	"github.com/kanopy-platform/code-generator/pkg/generators"
	"github.com/kanopy-platform/code-generator/pkg/generators/builder"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
	gengo "k8s.io/gengo/v2"
)

type rootCommand struct {
	GeneratedBuildTag  string
	InputDirs          []string
	LogLevel           string
	OutputFileBaseName string
}

func NewRootCommand() *cobra.Command {
	rootCommand := &rootCommand{}
	cmd := &cobra.Command{
		Use:               "kanopy-codegen",
		Short:             "Kanopy Builder code generator",
		PersistentPreRunE: rootCommand.prerun,
		RunE:              rootCommand.runE,
	}

	rootCommand.setupFlags(cmd)

	return cmd
}

func (r *rootCommand) setupFlags(cmd *cobra.Command) {
	flags := cmd.PersistentFlags()
	flags.StringVarP(&r.LogLevel, "log-level", "v", "info", "Configure log level")
	flags.StringSliceVarP(&r.InputDirs, "input-dirs", "i", nil, "Comma-separated list of import paths to get input types from.")
	flags.StringVarP(&r.OutputFileBaseName, "output-file-base", "O", "zz_generated_builders.go", "Base name (without .go suffix) for output files.")
	flags.StringVar(&r.GeneratedBuildTag, "build-tag", "ignore_autogenerated", "A Go build tag to use to identify files generated by this command. Should be unique.")
}

func (r *rootCommand) prerun(cmd *cobra.Command, args []string) error {
	logLevel, err := log.ParseLevel(r.LogLevel)
	if err != nil {
		return err
	}

	log.SetLevel(logLevel)
	return nil
}

func (r *rootCommand) runE(cmd *cobra.Command, args []string) error {
	headerLines := []string{
		fmt.Sprintf("//go:build !%s\n", r.GeneratedBuildTag),
		"/* DO NOT EDIT */",
		"/* autogenerated by kanopy-platform/code-generator */",
		"\n",
	}

	g := generators.New(&builder.BuilderPatternGeneratorFactory{OutputFileBaseName: r.OutputFileBaseName},
		generators.WithBoilerplate(strings.Join(headerLines, "\n")))
	return gengo.Execute(
		generators.NameSystems(),
		generators.DefaultNameSystem,
		g.Targets,
		r.GeneratedBuildTag,
		r.InputDirs,
	)
}
