package snippets

import (
	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func GenerateEmptyConstructor(t *types.Type, pointerReceiver bool) (string, generator.Args) {
	args := defaultGeneratorArgs(t, pointerReceiver)

	raw := `// New$.type|raw$ is an autogenerated constructor.
func New$.type|raw$() $.pointer$$.type|raw$ {
	o := $.ampersand$$.type|raw${}
	return o
}

`
	return raw, args
}

func GenerateConstructorForObjectMeta(t *types.Type) (string, generator.Args) {
	args := defaultGeneratorArgs(t, true)

	raw := `// New$.type|raw$ is an autogenerated constructor.
func New$.type|raw$(name string) *$.type|raw$ {
	o := &$.type|raw${}
	o.ObjectMeta.Name = name
	return o
}

`
	return raw, args
}

func defaultGeneratorArgs(t *types.Type, pointerReceiver bool) generator.Args {
	args := generator.Args{
		"type":      t,
		"pointer":   "",
		"ampersand": "",
	}

	if pointerReceiver {
		args["pointer"] = "*"
		args["ampersand"] = "&"
	}

	return args
}
