package snippets

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/gengo/generator"
)

func TestGenerateEmptyConstructor(t *testing.T) {
	t.Parallel()

	ctx, err := newTestGeneratorContext()
	require.NoError(t, err)

	test := newTestType(t, "SomeStruct")
	want := `// NewSomeStruct is an autogenerated constructor.
func NewSomeStruct(name string) *SomeStruct {
	o := &SomeStruct{}
	return o
}

`
	var b bytes.Buffer
	sw := generator.NewSnippetWriter(&b, ctx, "$", "$")
	sw.Do(GenerateEmptyConstructor(test))
	assert.NoError(t, sw.Error())
	assert.Equal(t, want, b.String())
}

func TestGenerateConstructorForObjectMeta(t *testing.T) {
	t.Parallel()

	ctx, err := newTestGeneratorContext()
	require.NoError(t, err)

	test := newTestType(t, "SomeStruct")
	want := `// NewSomeStruct is an autogenerated constructor.
func NewSomeStruct(name string) *SomeStruct {
	o := &SomeStruct{}
	o.ObjectMeta.Name = name
	return o
}

`
	var b bytes.Buffer
	sw := generator.NewSnippetWriter(&b, ctx, "$", "$")
	sw.Do(GenerateConstructorForObjectMeta(test))
	assert.NoError(t, sw.Error())
	assert.Equal(t, want, b.String())
}
