package snippets

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func TestGenerateConstructor(t *testing.T) {
	t.Parallel()

	ctx, err := newTestGeneratorContext()
	require.NoError(t, err)

	tests := []struct {
		ctx  *generator.Context
		t    *types.Type
		want string
	}{
		{
			ctx: ctx,
			t:   newTestType(t, "SomeStruct"),
			want: `// NewSomeStruct is an autogenerated constructor.
func NewSomeStruct(name string) *SomeStruct {
	o := &SomeStruct{}
	o.ObjectMeta.Name = name
	return o
}
`,
		},
	}

	for _, test := range tests {
		var b bytes.Buffer
		sw := generator.NewSnippetWriter(&b, test.ctx, "$", "$")
		sw.Do(GenerateConstructor(test.t))
		assert.NoError(t, sw.Error())
		assert.Equal(t, test.want, b.String())
	}
}
