package snippets

import (
	"bytes"
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func TestGenerateDeepCopyInto(t *testing.T) {
	t.Parallel()

	ctx, err := newTestGeneratorContext()
	require.NoError(t, err)

	tests := []struct {
		ctx     *generator.Context
		t       *types.Type
		wantErr error
		want    string
	}{
		{
			// nil pointer ctx
			ctx:     nil,
			t:       newTestNamespaceType(),
			wantErr: errors.New("nil pointer"),
		},
		{
			// nil pointer t
			ctx:     ctx,
			t:       nil,
			wantErr: errors.New("nil pointer"),
		},
		{
			ctx:     ctx,
			t:       newTestNamespaceType(),
			wantErr: nil,
			want: `// DeepCopyInto is an autogenerated function
func (in *Namespace) DeepCopyInto(out *Namespace) {
in.Namespace.DeepCopyInto(&out.Namespace)
}

`,
		},
	}

	for _, test := range tests {
		var b bytes.Buffer
		err := GenerateDeepCopyInto(test.ctx, test.t, &b)
		if test.wantErr != nil {
			assert.Error(t, err)
		} else {
			assert.NoError(t, err)
			assert.Equal(t, test.want, b.String())
		}
	}
}

func TestGenerateDeepCopy(t *testing.T) {
	t.Parallel()

	ctx, err := newTestGeneratorContext()
	require.NoError(t, err)

	tests := []struct {
		ctx     *generator.Context
		t       *types.Type
		wantErr error
		want    string
	}{
		{
			// nil pointer ctx
			ctx:     nil,
			t:       newTestNamespaceType(),
			wantErr: errors.New("nil pointer"),
		},
		{
			// nil pointer t
			ctx:     ctx,
			t:       nil,
			wantErr: errors.New("nil pointer"),
		},
		{
			ctx:     ctx,
			t:       newTestNamespaceType(),
			wantErr: nil,
			want: `// DeepCopy is an autogenerated function
func (in *Namespace) DeepCopy() *Namespace {
if in == nil {
return nil
}
out := new(Namespace)
in.DeepCopyInto(out)
return out
}

`,
		},
	}

	for _, test := range tests {
		var b bytes.Buffer
		err := GenerateDeepCopy(test.ctx, test.t, &b)
		if test.wantErr != nil {
			assert.Error(t, err)
		} else {
			assert.NoError(t, err)
			assert.Equal(t, test.want, b.String())
		}
	}
}
