package snippets

import (
	"errors"
	"io"

	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func GenerateDeepCopyInto(w io.Writer, ctx *generator.Context, t *types.Type) error {
	if t == nil {
		return errors.New("nil pointer")
	}

	args := generator.Args{
		"type": t,
	}

	raw := `// DeepCopyInto is an autogenerated function
func (in *$.type|raw$) DeepCopyInto(out *$.type|raw$) {
	in.$.type|raw$.DeepCopyInto(&out.$.type|raw$)
}

`
	return writeSnippetWithArgs(w, ctx, raw, args)
}

func GenerateDeepCopy(w io.Writer, ctx *generator.Context, t *types.Type) error {
	if t == nil {
		return errors.New("nil pointer")
	}

	args := generator.Args{
		"type": t,
	}

	raw := `// DeepCopy is an autogenerated function
func (in *$.type|raw$) DeepCopy() *$.type|raw$ {
	if in == nil {
		return nil
	}
	out := new($.type|raw$)
	in.DeepCopyInto(out)
	return out
}

`
	return writeSnippetWithArgs(w, ctx, raw, args)
}
