package snippets

import (
	"errors"
	"io"

	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func GenerateDeepCopyInto(ctx *generator.Context, t *types.Type, w io.Writer) error {
	if ctx == nil || t == nil {
		return errors.New("nil pointer")
	}

	args := generator.Args{
		"type": t,
	}

	sw := generator.NewSnippetWriter(w, ctx, "$", "$")

	sw.Do("// DeepCopyInto is an autogenerated function\n", nil)
	sw.Do("func (in *$.type|raw$) DeepCopyInto(out *$.type|raw$) {\n", args)
	sw.Do("in.$.type|raw$.DeepCopyInto(&out.$.type|raw$)\n", args)
	sw.Do("}\n\n", nil)

	return sw.Error()
}

func GenerateDeepCopy(ctx *generator.Context, t *types.Type, w io.Writer) error {
	if ctx == nil || t == nil {
		return errors.New("nil pointer")
	}

	args := generator.Args{
		"type": t,
	}

	sw := generator.NewSnippetWriter(w, ctx, "$", "$")

	sw.Do("// DeepCopy is an autogenerated function\n", nil)
	sw.Do("func (in *$.type|raw$) DeepCopy() *$.type|raw$ {\n", args)
	sw.Do("if in == nil {\n", nil)
	sw.Do("return nil\n", nil)
	sw.Do("}\n", nil)
	sw.Do("out := new($.type|raw$)\n", args)
	sw.Do("in.DeepCopyInto(out)\n", nil)
	sw.Do("return out\n", nil)
	sw.Do("}\n\n", nil)

	return sw.Error()
}
