package snippets

import (
	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func GenerateMarshalJSON(t *types.Type, schemeGroupVersionPackageAlias string) (string, generator.Args) {
	args := generator.Args{
		"type":  t,
		"alias": schemeGroupVersionPackageAlias,
	}

	raw := `// MarshalJSON is an autogenerated marshaling function, setting the TypeMeta.
func (o $.type|raw$) MarshalJSON() ([]byte, error) {
	o.$.type|raw$.TypeMeta = metav1.TypeMeta{Kind: "$.type|raw$", APIVersion: $.alias$.SchemeGroupVersion.String()}
	return json.Marshal(o.$.type|raw$)
}

`
	return raw, args
}
