package snippets

import (
	"bytes"
	"errors"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/gengo/generator"
	"k8s.io/gengo/types"
)

func TestGenerateSetter(t *testing.T) {
	t.Parallel()

	ctx, err := newTestGeneratorContext()
	require.NoError(t, err)

	namespaceType := newTestNamespaceType()

	tests := []struct {
		ctx       *generator.Context
		root      *types.Type
		member    types.Member
		hasParent bool
		embedded  *types.Type
		wantErr   error
		want      string
	}{
		{
			// nil pointer t
			ctx:     ctx,
			root:    nil,
			wantErr: errors.New("nil pointer"),
		},
		{
			// test default setter
			ctx:       ctx,
			root:      namespaceType,
			member:    namespaceType.Members[0].Type.Members[objectMetaMember].Type.Members[objectMetaNameMember], // Namespace -> EmbeddedNamespace -> ObjectMeta -> Name (string)
			hasParent: true,
			wantErr:   nil,
			want: `// WithName is an autogenerated setter function.
func (o *Namespace) WithName(in string) *Namespace {
o.Namespace.Name = in
return o
}

`,
		},
		{
			// test default setter, no parent
			ctx:       ctx,
			root:      namespaceType,
			member:    namespaceType.Members[0].Type.Members[objectMetaMember].Type.Members[objectMetaNameMember], // Namespace -> EmbeddedNamespace -> ObjectMeta -> Name (string)
			hasParent: false,
			wantErr:   nil,
			want: `// WithName is an autogenerated setter function.
func (o *Namespace) WithName(in string) *Namespace {
o.Name = in
return o
}

`,
		},
		{
			// test map setter
			ctx:       ctx,
			root:      namespaceType,
			member:    namespaceType.Members[0].Type.Members[objectMetaMember].Type.Members[objectMetaLabelsMember], // Namespace -> EmbeddedNamespace -> ObjectMeta -> Lables (map[string]string)
			hasParent: true,
			wantErr:   nil,
			want: `// WithLabels is an autogenerated setter function.
func (o *Namespace) WithLabels(in map[string]string) *Namespace {
o.Namespace.Labels = mergeMapStringString(o.Namespace.Labels, in)
return o
}

`,
		},
		// TODO slice without embedded
		// TODO slice with embedded
		// TODO struct without embedded
		// TODO struct with embedded
		{
			// test pointer to builtin
			ctx:       ctx,
			root:      namespaceType,
			member:    namespaceType.Members[0].Type.Members[objectMetaMember].Type.Members[objectMetaIntptrMember], // Namespace -> EmbeddedNamespace -> ObjectMeta -> Int64Ptr (*int64)
			hasParent: true,
			wantErr:   nil,
			want: `// WithIntptr is an autogenerated setter function.
func (o *Namespace) WithIntptr(in int) *Namespace {
o.Namespace.Intptr = &in
return o
}

`,
		},
	}

	for _, test := range tests {
		var b bytes.Buffer
		err := GenerateSetter(&b, test.ctx, test.root, test.member, test.hasParent, test.embedded)
		if test.wantErr != nil {
			assert.Error(t, err)
		} else {
			assert.NoError(t, err)
			assert.Equal(t, test.want, b.String())
		}
	}
}
